name: Mirror to GitLab

on:
  push:
    branches: ["**"]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Mirror to GitLab
        run: |
          git remote add gitlab https://pat:${{ secrets.GITLAB_TOKEN }}@gitlab.com/containerhive/test-project.git
          git push gitlab \
            --prune \
            "refs/remotes/origin/*:refs/heads/*" \
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
