name: Mirror to GitLab

on:
  push:
    branches: ["**"]
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitlab.com:containerhive/test-project.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
